feat(storybook): added links to figma and storybook
PhillipsAuctionHouse/seldon pull request #157
Opened 2024-05-31 18:38 UTC by constantinehuzenko

**Jira ticket**

[L3-2028](https://phillipsauctions.atlassian.net/browse/L3-2028)

**Screenshots**
![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/9e842192-8086-4d10-92e1-cac239b99bcd)
![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/dcaf3d9c-6539-4db7-8e0f-127a30caad94)
![image](https://github.com/PhillipsAuctionHouse/seldon/assets/26413122/59751fb4-3c8b-403d-ab8c-545aae5a5004)

**Summary**

Added overview jsdoc comment with Figma link to all components.

**Change List (describe the changes made to the files)**

- Added storybook and figma link to all represented components in Figma

**Acceptance Test (how to verify the PR)**

- Hover over the component name.
- Click on the Figma link.
- Verify that the Figma design matches the component.
- Locate the Dev Resources section and click on the link.
- Verify that the new page matches the Figma page.

**Regression Test**

- (Optional) Add verification steps to make sure this PR doesn't break old functionality

**Evidence of testing**

- Post logs, screenshots, etc

**Things to look for during review**

- [ ] Make sure all references to `phillips` class prefix is using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit test should be written and should have a coverage of 90% or higher in all areas.
- [ ] PR should link and close out an existing issue
- [ ] Make sure all commits messages follow convention and are appropriate for the changes

New Components

- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file

2024-06-03 20:17 UTC, davidicus approved these changes
This looks ok to me. I guess I misunderstood where we were setting the storybook link. I am not sure of the utility of adding a link to the page the user is already on.

2024-06-04 15:32 UTC, scottdickerson commented
remin

> This looks ok to me. I guess I misunderstood where we were setting the storybook link. I am not sure of the utility of adding a link to the page the user is already on.

I think @davidicus is right, now that I see it it doesn't make sense to link back to the current page.  @constantinehuzenko can you remove the storybook links?

2024-06-04 15:34 UTC, scottdickerson commented on src/components/Grid/Grid.tsx
> + * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=6226-1330&m=dev)
I think this is a more direct link and should be used on GridItem as well.

```suggestion
 * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=7274-9908&m=dev)
```

2024-06-04 15:36 UTC, scottdickerson commented on src/components/Input/Input.tsx
> + * [Figma Input Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=4433-163016&m=dev)
I think this is a more direct link.

```suggestion
 * [Figma Input Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=5730-11727&m=dev)
```

2024-06-04 15:37 UTC, scottdickerson commented on src/components/Link/Link.tsx
> + * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=4612-79026&m=dev)
```suggestion
 * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=5731-12815&m=dev)
```

2024-06-04 15:38 UTC, scottdickerson commented on src/components/LinkBlock/LinkBlock.tsx
> + * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=4612-79026&m=dev)
```suggestion
 * [Figma Link](https://www.figma.com/design/xMuOXOAKVt5HC7hgYjF3ot/Components-v2.0?node-id=5731-12815&m=dev)
```

2024-06-04 15:52 UTC, scottdickerson requested changes
Looks like SplitPanel didn't get updated to have a storybook link?  I'd use this link:

https://www.figma.com/design/Hp2FyltbOmRxTuw9kSwBAd/EPIC-About-Us?node-id=904-13262&t=k5gTlHC8QkLmwTFs-4

2024-06-04 15:54 UTC, scottdickerson commented
I think this is a `docs` change not a `feat` change.  We shouldn't need to publish a new release

2024-06-04 16:02 UTC, davidicus commented
> I think this is a `docs` change not a `feat` change. We shouldn't need to publish a new release

good catch

2024-06-05 17:40 UTC, scottdickerson approved these changes

2024-06-05 17:41 UTC, merged

2024-06-11 19:38 UTC, davidicus commented
:tada: This PR is included in version 1.24.0 :tada:

The release is available on:
- [GitHub release](https://github.com/PhillipsAuctionHouse/seldon/releases/tag/v1.24.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@phillips/seldon/v/1.24.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: