fix(accordion): L3-3274 remove unnecessary "collapsible" prop
PhillipsAuctionHouse/seldon pull request #276
Opened 2024-08-15 21:43 UTC by aahill50

**Jira ticket**

[L3-3274](https://phillipsauctions.atlassian.net/browse/L3-3274)

**Screenshots**
| Before | After |
| ------ | ----- |

| ![L3-3274 - before](https://github.com/user-attachments/assets/56a6c727-34af-436e-b7a9-02b1ea754b36) | ![L3-3274 - after](https://github.com/user-attachments/assets/fad1c3b8-72f8-44e3-9f11-dcee3590ecc6) |

**Summary**

Fixes the console error coming from the Accordion component. The error was a little misleading, it was complaining about the `collapsible` prop being passed to the DOM as a boolean instead of a string, but the error was actually caused by the fact that we didn't need to pass in the `collapsible` prop at all because the Accordion `type` was set to `multiple`. When the prop is `multiple`, the child components are already set to be collapsible, and I think that the `collapsible` prop we were passing in was being treated as an extra prop and getting passed all the way through, down to the `div` on the DOM. By removing the extra prop, the component still works the same and it eliminates that error. 

**Change List (describe the changes made to the files)**

- Additions, Changes, and Removals

**Acceptance Test (how to verify the PR)**

- Add step by step instructions on how to verify the change

**Regression Test**

- (Optional) Add verification steps to make sure this PR doesn't break old functionality

**Evidence of testing**

- Post logs, screenshots, etc

**Things to look for during review**

- [ ] PR title should correctly describe the most significant type of commit. I.e. `feat(scope): ...` if a `minor` release should be triggered.
- [ ] All commit messages follow convention and are appropriate for the changes
- [ ] All references to `phillips` class prefix are using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit tests should be written and should have a coverage of 90% or higher in all areas.

New Components

- [ ] Are there any [accessibility considerations](https://www.w3.org/WAI/ARIA/apg/patterns/) that need to be taken into account and tested?
- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file
- [ ] Import the component scss file into the `componentStyles.scss` file.

2024-08-16 17:18 UTC, aahill50 commented
I updated this PR to add a `variant` prop to Accordion instead of just removing the `collapsible` prop that was causing the issue. Now, the component accepts a `variant` prop and dynamically determines which `type` and `collapsible` props to pass to the underlying radix Accordion component

2024-08-16 19:30 UTC, scottdickerson commented on src/components/Accordion/Accordion.tsx
> +  if (variant === AccordionVariants.singleCollapsible) {
I would be tempted to do this as a switch statement in a standalone function, not sure if you agree

2024-08-16 19:31 UTC, scottdickerson approved these changes
LGTM

2024-08-16 19:31 UTC, scottdickerson commented on src/components/Accordion/Accordion.tsx
> +  if (variant === AccordionVariants.singleCollapsible) {
or at least extract it to a separately testable function and write a testcase specifically targeted at it.

2024-08-16 19:32 UTC, scottdickerson requested changes
@aahill50 probably should increase test coverage on the new code before merging.  Could you also fill out the rest of the sections of the PR template?

2024-08-19 16:50 UTC, scottdickerson approved these changes
LGTM

2024-08-19 20:58 UTC, merged

2024-08-19 20:59 UTC, davidicus commented
:tada: This issue has been resolved in version 1.38.5 :tada:

The release is available on:
- [GitHub release](https://github.com/PhillipsAuctionHouse/seldon/releases/tag/v1.38.5)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@phillips/seldon/v/1.38.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: