feat(header-animations) L3-3037 Header Animations Transitions
PhillipsAuctionHouse/seldon pull request #330
Opened 2024-09-23 21:58 UTC by adietrich3074

**Jira ticket**

[L3-3037](https://phillipsauctions.atlassian.net/browse/L3-3037)

**Summary**

Added css transitions and animations to desktop and mobile header.

**Change List (describe the changes made to the files)**

- Slide-up and slide-down animations added to accordions on mobile menu
- Slide out from left animation added to main menu on mobile
- Mobile search slide out animation and input styling fixed on mobile
- Slide-up and slide-down animations added on hover to Auctions and Departments nav items

**Acceptance Test (how to verify the PR)**

- Verify that the animations match expected behavior from [desktop protopie](https://cloud.protopie.io/p/1b0a7def5ee11e505e4808b4) and [mobile protopie](https://cloud.protopie.io/p/322a8627be4733482918eebf?sceneId=be3f9870-99e5-41f8-aaee-7e17394dba93)

**Things to look for during review**

- [ ] PR title should correctly describe the most significant type of commit. I.e. `feat(scope): ...` if a `minor` release should be triggered.
- [ ] All commit messages follow convention and are appropriate for the changes
- [ ] All references to `phillips` class prefix are using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit tests should be written and should have a coverage of 90% or higher in all areas.

New Components

- [ ] Are there any [accessibility considerations](https://www.w3.org/WAI/ARIA/apg/patterns/) that need to be taken into account and tested?
- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file
- [ ] Import the component scss file into the `componentStyles.scss` file.

2024-09-24 11:35 UTC, scottdickerson commented
The font weight of the search placeholder and text looks off: 
![image](https://github.com/user-attachments/assets/15fbda7e-c9c2-477a-a9bf-c5145b2938a3)

2024-09-24 11:38 UTC, scottdickerson commented
I'm seeing some weirdness with the mobile menu extending past the storybook:
![image](https://github.com/user-attachments/assets/88d1a84f-3ee8-4d72-94fc-b0a258565bad)

2024-09-24 12:55 UTC, scottdickerson commented on src/components/Navigation/NavigationItemTrigger/NavigationItemTrigger.tsx
> +        {/* </SSRMediaQuery.Media> */}
did this need to be removed?  Ideally it wouldn't render to the DOM for accessibility/screen readers

2024-09-24 12:57 UTC, scottdickerson requested changes
some UX changes

2024-09-24 14:25 UTC, adietrich3074 commented
> The font weight of the search placeholder and text looks off: ![image](https://private-user-images.githubusercontent.com/6663002/370265022-15fbda7e-c9c2-477a-a9bf-c5145b2938a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODgxMDksIm5iZiI6MTcyNzE4NzgwOSwicGF0aCI6Ii82NjYzMDAyLzM3MDI2NTAyMi0xNWZiZGE3ZS1jOWMyLTQ3N2EtYTliZi1jNTE0NWIyOTM4YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMTQyMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWRmZTI4MDYxZTRiNDhiOGRhMjE0ZTQ5MmIzMzI4ZDdjOGQ0OGIzMmI2ZThkMjJlZDQ2ZDBlMDJhOWY3OGU1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0CsI_ZHJdHWgTCuWlixHDC1dg868HgsnJGQzjIyHsw4)

I think this is caused by the scaling of the font token I was asked to change it to but this is correct based on the values for that input field in the figma:
`color: var(--Interactive-Static-CTA, #000);

/* Text/String 1 (Bold) */
font-family: var(--Font-Family-Body, Montserrat);
font-size: var(--Font-Size-Text-1, 1rem);
font-style: normal;
font-weight: 600;
line-height: var(--Font-Line-Height-String-1, 1.25rem); /* 125% */
letter-spacing: var(--Font-Character-Spacing-Text, 0rem);`

2024-09-24 14:44 UTC, adietrich3074 commented
> I'm seeing some weirdness with the right side of the mobile menu extending past the right edge of the screen: ![image](https://private-user-images.githubusercontent.com/6663002/370265832-88d1a84f-3ee8-4d72-94fc-b0a258565bad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODgxMDksIm5iZiI6MTcyNzE4NzgwOSwicGF0aCI6Ii82NjYzMDAyLzM3MDI2NTgzMi04OGQxYTg0Zi0zZWU4LTRkNzItOTRmYy1iMGEyNTg1NjViYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMTQyMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM5MDgxZjg5NTRlZWRiMWFhNWE4YzU1ZjlkMWY5ZDAxN2JlZTFjZDk5MDY4MWU4ZTlhZDcwNzAwMTg4MmUyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Xeo6yjIhx-v_sUUd2f34bhIsCetWvphIK9qyQJBoFck)

This looks like an issue with the desktop container in storybook. I'm not sure how to fix this because the issue doesn't occur in the regular dev tools view of the header or on my phone. My phone even displays the component in storybook without this misalignment in both portrait and landscape view

![Screenshot_20240924_104108_Chrome](https://github.com/user-attachments/assets/4a5b8b58-aae8-4302-8f4a-be60858e7e2d)
![Screenshot_20240924_103743_Chrome](https://github.com/user-attachments/assets/3d3c7d1d-41a8-45ba-bbda-b158d7c2999f)

The above screenshots are from my phone

2024-09-24 21:13 UTC, scottdickerson commented
> > The font weight of the search placeholder and text looks off: ![image](https://private-user-images.githubusercontent.com/6663002/370265022-15fbda7e-c9c2-477a-a9bf-c5145b2938a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODgxMDksIm5iZiI6MTcyNzE4NzgwOSwicGF0aCI6Ii82NjYzMDAyLzM3MDI2NTAyMi0xNWZiZGE3ZS1jOWMyLTQ3N2EtYTliZi1jNTE0NWIyOTM4YTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMTQyMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWRmZTI4MDYxZTRiNDhiOGRhMjE0ZTQ5MmIzMzI4ZDdjOGQ0OGIzMmI2ZThkMjJlZDQ2ZDBlMDJhOWY3OGU1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0CsI_ZHJdHWgTCuWlixHDC1dg868HgsnJGQzjIyHsw4)
> 
> I think this is caused by the scaling of the font token I was asked to change it to but this is correct based on the values for that input field in the figma: `color: var(--Interactive-Static-CTA, #000);
> 
> /* Text/String 1 (Bold) _/ font-family: var(--Font-Family-Body, Montserrat); font-size: var(--Font-Size-Text-1, 1rem); font-style: normal; font-weight: 600; line-height: var(--Font-Line-Height-String-1, 1.25rem); /_ 125% */ letter-spacing: var(--Font-Character-Spacing-Text, 0rem);`

@adietrich3074 can you reach out to design/UX to double check this to see if it's a token issue or this is a snowflake that we need to override

2024-09-25 13:46 UTC, scottdickerson approved these changes
LGTM

2024-09-25 13:46 UTC, merged

2024-09-25 13:47 UTC, davidicus commented
:tada: This issue has been resolved in version 1.62.0 :tada:

The release is available on:
- [GitHub release](https://github.com/PhillipsAuctionHouse/seldon/releases/tag/v1.62.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@phillips/seldon/v/1.62.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: