feat: L3-3145 pinch zoom component in seldon
PhillipsAuctionHouse/seldon pull request #346
Opened 2024-09-30 18:44 UTC by sgrund14

**Jira ticket**

[L3-3145(https://phillipsauctions.atlassian.net/browse/L3-3145)

**Screenshots**

https://github.com/user-attachments/assets/76198f78-376d-4d8b-8fa7-02b4ee50af48

**Summary**

A pinch zoom component in seldon
Nicely accompanied by the carousel component to form a pinch zoom carousel

To be accompanied by a remix PR shortly

**Change List (describe the changes made to the files)**

- New Pinch Zoom Component
- Stories demonstrating pinch zoom component when combined with both carousel and modal
- Tiny test suite (need better way to simulate wheel in / out, but otherwise not too much to test?)

**Acceptance Test (how to verify the PR)**

- Add step by step instructions on how to verify the change

**Regression Test**

- (Optional) Add verification steps to make sure this PR doesn't break old functionality

**Evidence of testing**

- Post logs, screenshots, etc

**Things to look for during review**

- [ ] PR title should correctly describe the most significant type of commit. I.e. `feat(scope): ...` if a `minor` release should be triggered.
- [ ] All commit messages follow convention and are appropriate for the changes
- [ ] All references to `phillips` class prefix are using the prefix variable
- [ ] All major areas have a `data-testid` attribute.
- [ ] Document all props with jsdoc comments
- [ ] All strings should be translatable.
- [ ] Unit tests should be written and should have a coverage of 90% or higher in all areas.

New Components

- [ ] Are there any [accessibility considerations](https://www.w3.org/WAI/ARIA/apg/patterns/) that need to be taken into account and tested?
- [ ] Default story called "Playground" should be created for all new components
- [ ] Create a jsdoc comment that has an Overview section and a link to the Figma design for the component
- [ ] Export the component and its typescript type from the `index.ts` file
- [ ] Import the component scss file into the `componentStyles.scss` file.

2024-09-30 20:28 UTC, scottdickerson commented on package.json
> +    "react-quick-pinch-zoom": "^5.1.0",
this isn't necessarily an indictment of this package, but I do see a much more widely used react zoom package according to npmtrends: 
![image](https://github.com/user-attachments/assets/dde622dc-b61f-4d44-b4ef-e04d546485dd)
Did you have a chance to check that one out?

2024-09-30 20:28 UTC, scottdickerson commented on src/components/Carousel/_carousel.scss
> +    &--cursor-pointer {
this is such a tailwindy thing :)

2024-09-30 20:29 UTC, scottdickerson commented on src/components/Carousel/_carousel.scss
> +    &--cursor-pointer {
could put in the `utils.scss` as a mixin to make it more scss-y

2024-09-30 20:30 UTC, scottdickerson commented on src/components/PinchZoom/PinchZoom.tsx
> +        cloneElement(children, {
might be good to check `isValidElement` before cloning.

2024-09-30 20:32 UTC, scottdickerson commented on vite.config.ts
> +    commonjsOptions: { transformMixedEsModules: true },
yikes, maybe another reason to check the other library out.  I think this is kind of an indicator that the library is a bit screwy.

2024-10-01 22:36 UTC, davidicus commented on src/components/Carousel/CarouselDots.tsx
> +import { ComponentProps, forwardRef, useCallback, useEffect, useState, useId } from 'react';
🤯 I did not know React exported something like this. Very cool

2024-10-02 02:31 UTC, davidicus approved these changes

2024-10-02 14:29 UTC, scottdickerson requested changes
This is working well, but I wonder if we should trigger zoom-in and zoom-out on a single click and use the `zoom-in` cursor when not zoomed in

2024-10-02 17:05 UTC, scottdickerson approved these changes
LGTM

2024-10-02 17:05 UTC, merged